/* ship:sw v1 — generated by ship. Do not hand-edit: every ship run regenerates it
 * with a content-hash cache name, so each deploy activates a fresh worker. */
const CACHE = "cos-ive-preview-c558f02f4581";
const CORE = ["./","./index.html"];
// Only THIS app's own stale caches (slug-<12hex>). CacheStorage is origin-wide and all
// apps share one origin, so a blunt "delete everything != CACHE" would wipe SIBLING apps'
// offline caches on every activate. Exact-shape match (not prefix — slug "app" must not
// match "app-two-…") evicts our own old deploys while leaving other apps untouched.
const OWN = "^cos-ive-preview-[0-9a-f]{12}$";
const OWN_RE = new RegExp(OWN);

self.addEventListener('install', (e) => {
  // Fail the install if precache fails: the OLD worker (and its intact offline cache)
  // stays in charge, and online users still get fresh code through its network-first
  // fetch handler. A half-cached new worker would silently degrade offline.
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(CORE)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE && OWN_RE.test(k)).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

// Network-first: online users always get the freshly deployed code; the cache is
// only the offline fallback. (Cache-first is how installed PWAs go stale.)
self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET') return;
  if (new URL(req.url).origin !== self.location.origin) return;
  e.respondWith(
    fetch(req)
      .then((res) => {
        const copy = res.clone();
        caches.open(CACHE).then((c) => c.put(req, copy)).catch(() => {});
        return res;
      })
      .catch(() => caches.match(req).then((r) => r || (req.mode === 'navigate' ? caches.match('./index.html') : Response.error())))
  );
});
