/* ship:sw v1 — generated by ship. Do not hand-edit: every ship run regenerates it
 * with a content-hash cache name, so each deploy activates a fresh worker. */
const CACHE = "class-booker-7ceeb69c9c47";
const CORE = ["./","./icon-any-192.png","./icon-any-512.png","./icon-maskable-192.png","./icon-maskable-512.png","./index.html","./manifest.json","./README.md"];

self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(CORE)).catch(() => {}).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

// Network-first: online users always get the freshly deployed code; the cache is
// only the offline fallback. (Cache-first is how installed PWAs go stale.)
self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET') return;
  if (new URL(req.url).origin !== self.location.origin) return;
  e.respondWith(
    fetch(req)
      .then((res) => {
        const copy = res.clone();
        caches.open(CACHE).then((c) => c.put(req, copy)).catch(() => {});
        return res;
      })
      .catch(() => caches.match(req).then((r) => r || (req.mode === 'navigate' ? caches.match('./index.html') : Response.error())))
  );
});
